---
version: '3'

services:
        visual:
                image: dockersamples/visualizer
                ports:
                        - "8080:8080"
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                deploy:
                        mode: global
                        placement:
                                constraints: [node.role == manager]
